apiVersion: v1
kind: Service
metadata:
  name: cart:microservice
spec:
  selector:
    app.kubernetes.io/name: cart:microservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 1004
   
