apiVersion: v1
kind: Service
metadata:
  name: zuul-api:microservice
spec:
  selector:
    app.kubernetes.io/name: zuul-api:microservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9999
   