apiVersion: v1
kind: Service
metadata:
  name: shoes:microservice
spec:
  selector:
    app.kubernetes.io/name: shoes:microservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 30012
      targetPort: 1002
   