apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-web-app:microservice
  labels:
    app: ui-web-app:microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-web-app:microservice
  template:
    metadata:
      labels:
        app: ui-web-app:microservice
    spec:
      containers:
      - name: shoes:microservice
        image: 863804372452.dkr.ecr.us-east-1.amazonaws.com/ui-web-app:latest
        ports:
        - containerPort: 8080
